=== filipecosta90/im2modelpy_api/blueprints/dats/schemas/schema_dats.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "object",
  "title": "The Root Schema",
  "required": [
    "description",
    "data_type",
    "dimensions",
    "margins",
    "sampling_rate",
    "roi_rectangle",
    "image_statistical"
  ],
  "properties": {
    "description": {
      "$id": "#/properties/description",
      "type": "string",
      "title": "The Description Schema",
      "default": "",
      "examples": [
        ""
      ],
      "pattern": "^(.*)$"
    },
    "data_type": {
      "$id": "#/properties/data_type",
      "type": "string",
      "title": "The Data_type Schema",
      "default": "",
      "examples": [
        "int32"
      ],
      "pattern": "^(.*)$"
    },
    "dimensions": {
      "$id": "#/properties/dimensions",
      "type": "object",
      "title": "The Dimensions Schema",
      "required": [
        "n_rows",
        "n_cols"
      ],
      "properties": {
        "n_rows": {
          "$id": "#/properties/dimensions/properties/n_rows",
          "type": "integer",
          "title": "The N_rows Schema",
          "default": 0,
          "examples": [
            1
          ]
        },
        "n_cols": {
          "$id": "#/properties/dimensions/properties/n_cols",
          "type": "integer",
          "title": "The N_cols Schema",
          "default": 0,
          "examples": [
            2
          ]
        }
      }
    },
    "margins": {
      "$id": "#/properties/margins",
      "type": "object",
      "title": "The Margins Schema",
      "required": [
        "nm",
        "px"
      ],
      "properties": {
        "nm": {
          "$id": "#/properties/margins/properties/nm",
          "type": "null",
          "title": "The Nm Schema",
          "default": null,
          "examples": [
            null
          ]
        },
        "px": {
          "$id": "#/properties/margins/properties/px",
          "type": "integer",
          "title": "The Px Schema",
          "default": 0,
          "examples": [
            0
          ]
        }
      }
    },
    "sampling_rate": {
      "$id": "#/properties/sampling_rate",
      "type": "object",
      "title": "The Sampling_rate Schema",
      "required": [
        "x_nm_per_pixel",
        "y_nm_per_pixel"
      ],
      "properties": {
        "x_nm_per_pixel": {
          "$id": "#/properties/sampling_rate/properties/x_nm_per_pixel",
          "type": "number",
          "title": "The X_nm_per_pixel Schema",
          "default": 0.0,
          "examples": [
            9e-05
          ]
        },
        "y_nm_per_pixel": {
          "$id": "#/properties/sampling_rate/properties/y_nm_per_pixel",
          "type": "number",
          "title": "The Y_nm_per_pixel Schema",
          "default": 0.0,
          "examples": [
            9e-05
          ]
        }
      }
    },
    "roi_rectangle": {
      "$id": "#/properties/roi_rectangle",
      "type": "object",
      "title": "The Roi_rectangle Schema",
      "required": [
        "x",
        "y",
        "n_rows",
        "n_cols",
        "center_x",
        "center_y"
      ],
      "properties": {
        "x": {
          "$id": "#/properties/roi_rectangle/properties/x",
          "type": "integer",
          "title": "The X Schema",
          "default": 0,
          "examples": [
            1
          ]
        },
        "y": {
          "$id": "#/properties/roi_rectangle/properties/y",
          "type": "integer",
          "title": "The Y Schema",
          "default": 0,
          "examples": [
            2
          ]
        },
        "n_rows": {
          "$id": "#/properties/roi_rectangle/properties/n_rows",
          "type": "integer",
          "title": "The N_rows Schema",
          "default": 0,
          "examples": [
            1
          ]
        },
        "n_cols": {
          "$id": "#/properties/roi_rectangle/properties/n_cols",
          "type": "integer",
          "title": "The N_cols Schema",
          "default": 0,
          "examples": [
            2
          ]
        },
        "center_x": {
          "$id": "#/properties/roi_rectangle/properties/center_x",
          "type": "integer",
          "title": "The Center_x Schema",
          "default": 0,
          "examples": [
            0
          ]
        },
        "center_y": {
          "$id": "#/properties/roi_rectangle/properties/center_y",
          "type": "integer",
          "title": "The Center_y Schema",
          "default": 0,
          "examples": [
            0
          ]
        }
      }
    },
    "image_statistical": {
      "$id": "#/properties/image_statistical",
      "type": "object",
      "title": "The Image_statistical Schema",
      "required": [
        "mean",
        "stddev"
      ],
      "properties": {
        "mean": {
          "$id": "#/properties/image_statistical/properties/mean",
          "type": "array",
          "title": "The Mean Schema",
          "items": {
            "$id": "#/properties/image_statistical/properties/mean/items",
            "type": "integer",
            "title": "The Items Schema",
            "default": 0,
            "examples": [
              1
            ]
          }
        },
        "stddev": {
          "$id": "#/properties/image_statistical/properties/stddev",
          "type": "array",
          "title": "The Stddev Schema",
          "items": {
            "$id": "#/properties/image_statistical/properties/stddev/items",
            "type": "integer",
            "title": "The Items Schema",
            "default": 0,
            "examples": [
              1
            ]
          }
        }
      }
    }
  }
}

=== filipecosta90/im2modelpy_api/blueprints/dats/schemas/input_request_dats.json
{ 
  "description" : "",
  "data_type" : "int32",
  "dimensions" : { "n_rows": 444, "n_cols": 444 },
  "margins" : { "nm" : null, "px" : 0 },
  "sampling_rate" : { "x_nm_per_pixel" : 0.00009, 
  "y_nm_per_pixel" : 0.00009
  },
  "roi_rectangle" : { "x": 1, "y": 2, "n_rows": 1, "n_cols": 2, "center_x" :0 , "center_y" : 0 },
  "image_statistical" : { "mean" : [1], "stddev" : [1] }
}
